-- ============================================
-- SCRIPT 17: FIX OLS PERMISSIONS FOR ALL USERS
-- Run as SYS
-- ============================================

ALTER SESSION SET CONTAINER = FREEPDB1;
SET SERVEROUTPUT ON;

BEGIN
    DBMS_OUTPUT.PUT_LINE('Fixing OLS Permissions...');
    
    -- LIBRARY user needs FULL to query user_info for auth
    SA_USER_ADMIN.SET_USER_PRIVS('LIBRARY_POLICY', 'LIBRARY', 'FULL');
    SA_USER_ADMIN.SET_USER_LABELS('LIBRARY_POLICY', 'LIBRARY', 'TS:LIB,HR,FIN:HQ');
    DBMS_OUTPUT.PUT_LINE('LIBRARY: FULL privileges granted.');
    
    -- ADMIN_USER needs FULL access
    SA_USER_ADMIN.SET_USER_PRIVS('LIBRARY_POLICY', 'ADMIN_USER', 'FULL');
    SA_USER_ADMIN.SET_USER_LABELS('LIBRARY_POLICY', 'ADMIN_USER', 'TS:LIB,HR,FIN:HQ');
    DBMS_OUTPUT.PUT_LINE('ADMIN_USER: FULL privileges granted.');
    
    -- LIBRARIAN_USER - can see up to CONFIDENTIAL
    SA_USER_ADMIN.SET_USER_PRIVS('LIBRARY_POLICY', 'LIBRARIAN_USER', NULL);
    SA_USER_ADMIN.SET_USER_LABELS('LIBRARY_POLICY', 'LIBRARIAN_USER', 'CONF:LIB:HQ');
    DBMS_OUTPUT.PUT_LINE('LIBRARIAN_USER: Label set to CONF.');
    
    -- STAFF_USER - can see up to INTERNAL
    SA_USER_ADMIN.SET_USER_PRIVS('LIBRARY_POLICY', 'STAFF_USER', NULL);
    SA_USER_ADMIN.SET_USER_LABELS('LIBRARY_POLICY', 'STAFF_USER', 'INT:LIB:BR_A');
    DBMS_OUTPUT.PUT_LINE('STAFF_USER: Label set to INT.');
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('All permissions fixed successfully.');
    
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/

EXIT;
