BEGIN
    EXECUTE IMMEDIATE 'CREATE USER sec_admin IDENTIFIED BY SecAdmin123 DEFAULT TABLESPACE users QUOTA UNLIMITED ON users';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1920 THEN
             EXECUTE IMMEDIATE 'ALTER USER sec_admin IDENTIFIED BY SecAdmin123 ACCOUNT UNLOCK';
        ELSE
             RAISE;
        END IF;
END;
/
GRANT CREATE SESSION TO sec_admin;
GRANT DV_OWNER TO sec_admin;
GRANT EXECUTE ON DVSYS.DBMS_MACADM TO sec_admin;
GRANT EXECUTE ON DVSYS.DBMS_MACUTL TO sec_admin;
exit;
