BEGIN
    EXECUTE IMMEDIATE 'CREATE USER dv_owner IDENTIFIED BY DVOwner123 DEFAULT TABLESPACE users QUOTA UNLIMITED ON users';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1920 THEN
             EXECUTE IMMEDIATE 'ALTER USER dv_owner IDENTIFIED BY DVOwner123 ACCOUNT UNLOCK';
        ELSE
             RAISE;
        END IF;
END;
/
GRANT CREATE SESSION TO dv_owner;
exit;
